OSSP (Multi-omics integration via Spectral decomposition on Self-diffusion network)
OSSP is an R package implementing an unsupervised framework for integrating cancer multi-omics data.

Overview
Here, we propose OSSP, an unsupervised framework for integrating cancer multi-omics data. OSSP works in three main steps:

1.Self-diffusion similarity network:
The input multi-omics data is converted into a patient-to-patient similarity network. A self-diffusion process is applied to enhance similarity measurement.

2.Spectral decomposition for integration:
Eigenvalues are selected from the enhanced network via spectral decomposition to integrate multiple omics datasets.

3.Clustering and molecular characterization:
A clustering method (e.g., K-means) is applied on the integrated data to obtain patient subtypes, followed by molecular characterization of each subtype.


Installation
You can install the package directly from GitHub:
# install.packages("devtools") # if not installed
devtools::install_github("Duanx-lab/OSSP")
